defaults:
  - override hydra/launcher: joblib
env_id: Ant-v4
batch_size: 256
train_n_episodes: 1000
warm_up_episodes: 50
gamma: 0.99
train_steps: 1
target_update_freq: 10
learning_rate: 0.0001
actor_learning_rate: 0.001
replay_buffer_capacity: 10000
width: 256
grid: 5
method: "MLP"
seed: 2
tau: 0.01
device: cuda
policy_update_frequency: 5
exploration_noise: 0.1
exploration_epsilon: 0.1
train: true
test: true
test_n_episodes: 20
results_dir: "results"
plots_dir: "plots"
runs_dir: "runs"
models_dir: "models"
figures_dir: "figures"
action_buffer: 5
tolerance: 5
max_delta_loss: 0.05
grid_update_frequency: 25
dimension_wrapper_number: 0
num_legs: 4