defaults:
  - override hydra/launcher: joblib
env_id: ContinuousCartPoleEnv
batch_size: 256
train_n_episodes: 1000
warm_up_episodes: 50
gamma: 0.99
train_steps: 1
target_update_freq: 10
learning_rate: 0.01
actor_learning_rate: 0.001
replay_buffer_capacity: 10000
width: 400
grid: 5
method: "KAN"
seed: 0
tau: 0.01
device: cpu
policy_update_frequency: 5
exploration_noise: 0.1
exploration_epsilon: 0.1
train: true
test: true
test_n_episodes: 5
results_dir: "results"
plots_dir: "plots"
runs_dir: "runs"
models_dir: "models"
figures_dir: "figures"
action_buffer: 5
tolerance: 5
max_delta_loss: 0.05
grid_update_frequency: 25