defaults:
  - override hydra/launcher: joblib
env_id: MorphingAnt
num_legs: 3
healthy_reward: 0.1
render: false
# network
method: "EfficientKAN"
width: 256
# training
device: cpu
seed: 0
train: true
test: true
train_n_episodes: 1000
warm_up_episodes: 50
test_n_episodes: 10
# hyperparameters
batch_size: 256
learning_rate: 0.0001
actor_learning_rate: 0.001
replay_buffer_capacity: 10000
grid: 5
tau: 0.01
gamma: 0.99
policy_update_frequency: 5
grid_update_frequency: 25
exploration_epsilon: 0.1
noise_mean: 0.0
noise_std: 0.2
action_buffer: 5
dimension_wrapper_number: 0
# early stopping
tolerance: 5
max_delta_loss: 0.05
# folder names
results_dir: "results"
plots_dir: "plots"
runs_dir: "runs"
models_dir: "models"
figures_dir: "figures"