defaults:
  - override hydra/launcher: joblib
env_id: Ant-v4
batch_size: 256
train_n_episodes: 20
warm_up_episodes: 2
gamma: 0.99
train_steps: 1
target_update_freq: 10
learning_rate: 0.0005
actor_learning_rate: 0.0005
replay_buffer_capacity: 10000
width: 8
grid: 5
method: "KAN"
seed: 0
tau: 0.01
device: cpu
policy_update_frequency: 2
exploration_noise: 0.1
exploration_epsilon: 0.1
train: false
test: true
test_n_episodes: 5